<?php
/**************************************************
 *		extension.inc
 *		-------------------                         
 *      Разработка: phpBB Group.
 *      Оптимизация под WAP: Гутник Игорь ( чел ).
 *          2010 год
 *		简体中文：爱疯的云
 **************************************************/ 

if ( !defined('IN_PHPBB') )
{
	die("Hacking attempt");
}

header("Content-Type: text/html; charset=UTF-8");
$phpEx = "php";
$starttime = 0;

?>